/**
 * Script para cargar variables de entorno y generar el archivo environment.ts dinámicamente
 */
const fs = require('fs');
const path = require('path');
require('dotenv').config();

const targetPath = path.join(__dirname, '..', 'src', 'app', 'environments', 'environment.ts');
const envScriptPath = path.join(__dirname, '..', 'src', 'assets', 'env.js');

// Obtener variables de entorno con defaults seguros
const envConfig = {
  API_URL: process.env.API_URL || 'http://localhost:5000',
  ENV_NAME: process.env.ENV_NAME || 'development',
  PRODUCTION: process.env.PRODUCTION === 'true'
};

// Generate env.js for runtime configuration (placeholder for future features)
const envJsContent = `// Runtime environment configuration
// Generated by scripts/load-env.js - Do not edit manually
window.__ENV__ = {
  apiUrl: '${envConfig.API_URL}',
  envName: '${envConfig.ENV_NAME}'
};
`;

// Generar contenido del archivo
const envConfigFile = `// src/app/environments/environment.ts
// Este archivo es generado automáticamente por scripts/load-env.js
// No editar manualmente

/**
 * Interfaz para la configuración del ambiente
 */
export interface Environment {
  /** URL base de la API backend */
  apiUrl: string;
  /** Duración de la autenticación en milisegundos */
  authDurationMs: number;
  /** Google Maps API Key */
  googleMapsApiKey: string;
  /** Configuración de seguridad */
  security: {
    /** Forzar HTTPS */
    forceHttps: boolean;
    /** Habilitar CSP (Content Security Policy) */
    enableCSP: boolean;
    /** Habilitar validación estricta de tokens */
    strictTokenValidation: boolean;
  };
  /** Configuración de features */
  features: {
    /** Habilitar analytics */
    enableAnalytics: boolean;
  };
  /** Nombre del ambiente */
  envName: string;
  /** Indica si es producción */
  production: boolean;
}

/**
 * Configuración de la aplicación
 * Los valores se cargan desde variables de entorno (.env)
 */
export const environment: Environment = {
  apiUrl: '${envConfig.API_URL}',
  authDurationMs: 24 * 60 * 60 * 1000, // 1 día
  googleMapsApiKey: '', // Not used in current version
  security: {
    forceHttps: ${envConfig.PRODUCTION},
    enableCSP: ${envConfig.PRODUCTION},
    strictTokenValidation: ${envConfig.PRODUCTION},
  },
  features: {
    enableAnalytics: ${envConfig.PRODUCTION},
  },
  envName: '${envConfig.ENV_NAME}',
  production: ${envConfig.PRODUCTION},
};
`;

try {
  // Crear directorio si no existe
  const dirPath = path.dirname(targetPath);
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }

  // Write environment.ts
  fs.writeFileSync(targetPath, envConfigFile, { encoding: 'utf8' });

  // Write env.js for runtime Google Maps API key
  const assetsDir = path.dirname(envScriptPath);
  if (!fs.existsSync(assetsDir)) {
    fs.mkdirSync(assetsDir, { recursive: true });
  }
  fs.writeFileSync(envScriptPath, envJsContent, { encoding: 'utf8' });

  console.log('✅ Environment configuration loaded successfully!');
  console.log(`📁 File generated: ${targetPath}`);
  console.log(`📁 File generated: ${envScriptPath}`);
  console.log(`🔗 API URL: ${envConfig.API_URL}`);
  console.log(`🎯 Environment: ${envConfig.ENV_NAME}`);
  console.log(`🏭 Production: ${envConfig.PRODUCTION}`);
} catch (error) {
  console.error('❌ Error generating environment file:', error);
  process.exit(1);
}
